version: '3.8'
services:
  web:
    image: nginx
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./style.css:/usr/share/nginx/html/style.css